# Description shown in /help
description = "Add the link description if missing"

# The prompt to execute.
# {{args}} will be replaced by the content of a @file or "quoted text".
prompt = '''
Find every unordered list item which contains only a hyperlink element by regex matching.
In regex: ^\s*[-*+]\s+\[[^\]]*\]\([^)]*\)\s*$
Add the descriptions for each such item just after the hyperlink element.

The description string should be quoted from the linked site as much as possible. 
The description string should start with "A" or "The", and must omit the trailing period.
Don't repeat the item name in the description string.

Expected Format: 
* [IP](https://en.wikipedia.org/wiki/Internet_Protocol) - The network layer communications protocol in the Internet protocol suite

Input File:
{{args}}
'''
