# Description shown in /help
description = "Add the link description if missing"

# The prompt to execute.
# {{args}} will be replaced by the content of a @file or "quoted text".
prompt = '''
Find every unordered list item which contains only a hyperlink element by regex matching.
In regex: ^\s*[-*+]\s+\[[^\]]*\]\([^)]*\)\s*$
Add the descriptions for each such item just after the hyperlink element.

Input File:
{{args}}
'''
