# Description shown in /help
description = "Add the link description if missing"

# The prompt to execute.
# {{args}} will be replaced by the content of a @file or "quoted text".
prompt = """
Find markdown enumerated items which consist of only hyperlinks and don't have descriptions of them.
Add the descriptions for each such item just after the hyperlink element.
Replace only the targeted items.

The description string should be quoted from the linked site as much as possible. 
The description string should start with "A" or "The".
Don't repeat the item name in the description string.
Omit the trailing period.

Expected Format: 
* [IP](https://en.wikipedia.org/wiki/Internet_Protocol) - The network layer communications protocol in the Internet protocol suite

Input File:
{{args}}
"""
