# Description shown in /help
description = "Update timeline classification"

# The prompt to execute.
# {{args}} will be replaced by the content of a @file or "quoted text".
prompt = """
For each paragraph in the markdown provided, classify the timeline event into the following classes and put the corresponding emoji at the beginning of the paragraph. 
The paragraph is one or more statement lines delimited by a blank line. The existing emoji can be replaced if it is not proper.

Classes:

ğŸ¢: Business Administration, Development Methodology, Management
ğŸŒ: Web Technology incl. Web Frameworks
â˜ï¸: Cloud, Cloud Native, Container, DevOps/SRE
ğŸ”: Security, Privacy
ğŸ›: Malware, Virus, Security Incident
ğŸ“Š: Data Science, Databases, Data Platforms
ğŸ§ : AI, Machine Learning, Large Language Models
ğŸ–¥ï¸: Shell, Scripting, Termial, IDE, Developer Productivity
âš™ï¸: System Administration, OS, VM, Network Infraatructure
ğŸ“œ: Programming Paradigms, Programming Concepts, Libraries
ğŸ©·: Others

Overwrite the original markdown.
The newline character must exist at the end of the file.

Input File:
{{args}}
"""
