# Description shown in /help
description = "Write the link description if it is not provided"

# The prompt to execute.
# {{args}} will be replaced by the content of a @file or "quoted text".
prompt = """
For each markdown item provided, add the description string just after the hyperlink element
if the item have the hyperlink without its description.

Expected Format: 
* [IP](https://en.wikipedia.org/wiki/Internet_Protocol) - The network layer communications protocol in the Internet protocol suite

The description string should be quoted from the linked site as much as possible. 
The description string should start with "A" or "The".
Don't repeat the item name in the description string.
Omit the trailing period.

Overwrite the original markdown.
The newline character must exist at the end of the file.

Input File:
{{args}}
"""
